# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy static content to Nginx's default static content directory
COPY index.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

